
opsman_credentials: &opsman_credentials
  SKIP_SSL_VALIDATION: ((opsman.skip-ssl-validation))
  OPSMAN_URL: ((opsman.url))
  OPSMAN_USERNAME: ((opsman.username))
  OPSMAN_PASSWORD: ((opsman.password))
  OPSMAN_PRIVATE_KEY: ((opsman.private-key))

s3_credentials: &s3_credentials
  bucket: ((storage.backup-bucket))
  region_name: ((storage.region))
  access_key_id: ((aws_credentials.access_key_id))
  secret_access_key: ((aws_credentials.secret_access_key))
  endpoint: ((storage.endpoint))

jobs:
- name: cleanup-bosh-director
  serial: true
  plan:
  - in_parallel:
    - get: bbr-pipeline-tasks-repo
    - get: bbr-concourse-repo

  - task: cleanup-director
    file: bbr-concourse-repo/bbr-concourse-backup-task.yml
    params:
      <<: *opsman_credentials

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git
    branch: master
- name: bbr-concourse-repo
  type: git
  source:
    uri: https://github.com/ambercs/bbr-concourse.git
    branch: main
- name: concourse-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    regexp: concourse-backup_(.*).tar
- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet.api_token))
    product_slug: p-bosh-backup-and-restore