opsman_credentials: &opsman_credentials
  OM_SKIP_SSL_VALIDATION: ((opsman.skip-ssl-validation))
  OM_URL: ((opsman.url))
  OM_USERNAME: ((opsman.username))
  OM_PASSWORD: ((opsman.password))
  OM_PRIVATE_KEY: ((opsman.private-key))

s3_credentials: &s3_credentials
  bucket: ((storage.backup-bucket))
  region_name: ((storage.region))
  access_key_id: ((aws_credentials.access_key_id))
  secret_access_key: ((aws_credentials.secret_access_key))
  endpoint: ((storage.endpoint))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git
    branch: master
- name: bbr-concourse-repo
  type: git
  source:
    uri: https://github.com/ambercs/platform-tools.git
    branch: main
- name: concourse-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    regexp: concourse-backup_(.*).tar
- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet.api_token))
    product_slug: p-bosh-backup-and-restore

jobs:
- name: bbr-backup-concourse
  serial: true
  plan:
  - in_parallel:
    - get: bbr-pipeline-tasks-repo
    - get: bbr-concourse-repo
    - get: bbr-release
  - task: check-opsman-status
    file: bbr-pipeline-tasks-repo/tasks/check-opsman-status/task.yml
    params:
      <<: *opsman_credentials
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - task: bbr-backup-concourse
    file: bbr-concourse-repo/bbr-concourse/bbr-concourse-backup-task.yml
    params:
      DEPLOYMENT_NAME: concourse
      <<: *opsman_credentials
    on_failure:
      task: bbr-cleanup-concourse
      file: bbr-concourse-repo/bbr-concourse/bbr-concourse-cleanup-task.yml
      params:
        DEPLOYMENT_NAME: concourse
        <<: *opsman_credentials
  - put: concourse-backup-bucket
    params:
      file: concourse-backup-artifact/concourse-backup_*.tar
