
jobs:
- name: cleanup-bosh-director
  serial: true
  plan:
  - in_parallel:
    - get: bosh-repave-repo
    - get: bosh-mgmt
    - get: scheduler
      trigger: true
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["*.tgz"]
  - task: cleanup-director
    image: platform-automation-image
    file: bosh-mgmt/bosh-repave/cleanup-bosh-director.yml
    params:
      SKIP_SSL_VALIDATION: ((opsman.skip-ssl-validation))
      OPSMAN_URL: ((opsman.url))
      OPSMAN_USERNAME: ((opsman.username))
      OPSMAN_PASSWORD: ((opsman.password))
      OPSMAN_PRIVATE_KEY: ((opsman.private-key))

- name: repave
  serial: true
  plan:
  - in_parallel:
    - get: bosh-mgmt
    - get: bosh-repave-repo
    - get: scheduler
      trigger: true

  - task: repave
    file: bosh-mgmt/bosh-repave/repave-diego-cells.yml
    params:
      SKIP_SSL_VALIDATION: ((opsman.skip-ssl-validation))
      OPSMAN_URL: ((opsman.url))
      OPSMAN_USERNAME: ((opsman.username))
      OPSMAN_PASSWORD: ((opsman.password))
      OPSMAN_PRIVATE_KEY: ((opsman.private-key))
      DEPLOYMENT: "cf"

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: bosh-repave-repo
  type: git
  source:
    uri: https://github.com/pivotalservices/bosh-repave.git
    branch: master
- name: bosh-mgmt
  type: git
  source:
    uri: https://github.com/ambercs/platform-tools.git
    branch: main
- name: scheduler
  type: time
  source:
    interval: 168h
    start: 5:00PM
    stop: 6:00PM
    location: America/Chicago

- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: platform-automation
    product_version: 5\..*
